version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
  #    volumes:
  #      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9091:9091"
    command: server /data --console-address ":9091"
#    volumes:
#      - minio_data:/data
#
#volumes:
#  db_data:
#  minio_data:
